tap "dnicolson/bluetoothkeyboardenhancer"
tap "gromgit/fuse"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "potatolabs/git-redate"
brew "adr-tools"
brew "asdf"
brew "atomicparsley"
brew "autoconf"
brew "automake"
brew "awscli"
brew "bandcamp-dl"
brew "bash"
brew "bat"
brew "broot"
brew "certbot"
brew "cloc"
brew "coreutils"
brew "dnicolson/bluetoothkeyboardenhancer/bluetoothkeyboardenhancer"
brew "dockutil"
brew "duti"
brew "ffmpeg"
brew "fish"
brew "git"
brew "gnupg"
brew "go"
brew "gromgit/fuse/ifuse-mac"
brew "gromgit/fuse/rclone-mac"
brew "gromgit/fuse/sshfs-mac"
brew "gti"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "libimobiledevice"
brew "libusbmuxd", args: ["HEAD"]
brew "lynx"
brew "mackup"
brew "mas"
brew "maven"
brew "memcached", restart_service: true
brew "mp3splt"
brew "mysql", restart_service: true
brew "nmap"
brew "perl"
brew "php", restart_service: true
brew "postgresql", restart_service: true
brew "potatolabs/git-redate/git-redate"
brew "pv"
brew "redis", restart_service: true
brew "ripgrep"
brew "telnet"
brew "tig"
brew "tree"
brew "watchman"
brew "wget"
brew "xz"
brew "youtube-dl"
brew "zlib"
brew "zsh"
cask "1password"
cask "adobe-creative-cloud"
cask "adoptopenjdk8"
cask "aerial"
cask "airbuddy"
cask "alfred"
cask "ankiapp-anki"
cask "appcleaner"
cask "asset-catalog-tinkerer"
cask "bbedit"
cask "betterzip"
cask "bitbar"
cask "brewservicesmenubar"
cask "cakebrew"
cask "calibre"
cask "deepl"
cask "devutils"
cask "docker"
cask "dropbox"
cask "firefox"
cask "ghidra"
cask "go2shell"
cask "google-chrome"
cask "google-chrome-canary"
cask "hex-fiend"
cask "hyper"
cask "imazing"
cask "insomnia"
cask "intellij-idea"
cask "ios-app-signer"
cask "iterm2"
cask "itsycal"
cask "kaleidoscope"
cask "moneymoney"
cask "openemu"
cask "launchcontrol"
cask "macfuse"
cask "messenger"
cask "mimestream"
cask "paragon-ntfs"
cask "playonmac"
cask "proxyman"
cask "pixelsnap"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "rar"
cask "raycast"
cask "rocket"
cask "runjs"
cask "script-debugger"
cask "sequel-ace"
cask "skype"
cask "sloth"
cask "sublime-text"
cask "suspicious-package"
cask "swiftdefaultappsprefpane"
cask "tableplus"
cask "tower2"
cask "transmit4"
cask "typora"
cask "ubersicht"
cask "visual-studio-code"
cask "vlc"
cask "vmware-fusion"
cask "webpquicklook"
cask "xld"
cask "zoom"
mas "Apple Configurator 2", id: 1037126344
mas "Deliveries", id: 924726344
mas "Download Buddy", id: 802165887
mas "Gitfox", id: 1475511261
mas "Icon Slate", id: 439697913
mas "Infuse", id: 1136220934
mas "Key Codes", id: 414568915
mas "Magnet", id: 441258766
mas "Mate Translate", id: 1005088137
mas "ReadKit", id: 588726889
mas "Slack", id: 803453959
mas "Streaks", id: 963034692
mas "TickTick", id: 966085870
mas "The Unarchiver", id: 425424353
mas "ToothFairy", id: 1191449274
mas "Xcode", id: 497799835
